import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className="bg-white/80 backdrop-blur-sm border-b border-white/20 sticky top-0 z-50">
					<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
						<div className="flex items-center justify-between">
							<Link href="/">
								<h1 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">Kram</h1>
							</Link>
							<nav className="hidden md:flex space-x-8 text-gray-600">
								<Link href="/" className="hover:text-blue-600 transition-colors">
									หน้าแรก
								</Link>
								<Link href="/generate" className="hover:text-blue-600 transition-colors">
									สร้างลายผ้า
								</Link>
								<Link href="/gallery" className="hover:text-blue-600 transition-colors">
									Gallery
								</Link>
							</nav>
						</div>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
